// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgentAPI.DataModels;

namespace TravelAgentAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200716110806_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelAgentAPI.DataModels.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.ClientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientTypes");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Arrival")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.FlightBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InBookingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InSchedulerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InSeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OutBookingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OutFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutFlightSchedulerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutSeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientID");

                    b.HasIndex("InFlightId");

                    b.HasIndex("InSchedulerId");

                    b.HasIndex("InSeatId");

                    b.HasIndex("OutFlightId");

                    b.HasIndex("OutFlightSchedulerId");

                    b.HasIndex("OutSeatId");

                    b.ToTable("FlightBookings");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.FlightScheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JourneyTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightSchedulers");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.FlightBooking", b =>
                {
                    b.HasOne("TravelAgentAPI.DataModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgentAPI.DataModels.Flight", "InFlight")
                        .WithMany()
                        .HasForeignKey("InFlightId");

                    b.HasOne("TravelAgentAPI.DataModels.FlightScheduler", "InScheduler")
                        .WithMany()
                        .HasForeignKey("InSchedulerId");

                    b.HasOne("TravelAgentAPI.DataModels.Seat", "InSeat")
                        .WithMany()
                        .HasForeignKey("InSeatId");

                    b.HasOne("TravelAgentAPI.DataModels.Flight", "OutFlight")
                        .WithMany()
                        .HasForeignKey("OutFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgentAPI.DataModels.FlightScheduler", "OutFlightScheduler")
                        .WithMany()
                        .HasForeignKey("OutFlightSchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgentAPI.DataModels.Seat", "OutSeat")
                        .WithMany()
                        .HasForeignKey("OutSeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.FlightScheduler", b =>
                {
                    b.HasOne("TravelAgentAPI.DataModels.Flight", null)
                        .WithMany("FlightSchedulers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAgentAPI.DataModels.Seat", b =>
                {
                    b.HasOne("TravelAgentAPI.DataModels.Flight", null)
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
